// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	organization "github.com/DataSemanticHub/services/app/system-service/api/internal/handler/organization"
	user "github.com/DataSemanticHub/services/app/system-service/api/internal/handler/user"
	user_management "github.com/DataSemanticHub/services/app/system-service/api/internal/handler/user_management"
	user_public "github.com/DataSemanticHub/services/app/system-service/api/internal/handler/user_public"
	"github.com/DataSemanticHub/services/app/system-service/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthCheckHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 创建组织
					Method:  http.MethodPost,
					Path:    "/organization",
					Handler: organization.CreateOrgHandler(serverCtx),
				},
				{
					// 获取组织详情
					Method:  http.MethodGet,
					Path:    "/organization/:id",
					Handler: organization.GetOrgDetailHandler(serverCtx),
				},
				{
					// 更新组织
					Method:  http.MethodPut,
					Path:    "/organization/:id",
					Handler: organization.UpdateOrgHandler(serverCtx),
				},
				{
					// 删除组织
					Method:  http.MethodDelete,
					Path:    "/organization/:id",
					Handler: organization.DeleteOrgHandler(serverCtx),
				},
				{
					// 获取部门用户
					Method:  http.MethodGet,
					Path:    "/organization/:id/users",
					Handler: organization.GetOrgUsersHandler(serverCtx),
				},
				{
					// 移动组织
					Method:  http.MethodPost,
					Path:    "/organization/move",
					Handler: organization.MoveOrgHandler(serverCtx),
				},
				{
					// 获取组织架构树
					Method:  http.MethodGet,
					Path:    "/organization/tree",
					Handler: organization.GetOrgTreeHandler(serverCtx),
				},
				{
					// 删除用户辅助部门
					Method:  http.MethodDelete,
					Path:    "/user/:userId/aux-dept/:deptId",
					Handler: organization.RemoveUserAuxDeptHandler(serverCtx),
				},
				{
					// 添加用户辅助部门
					Method:  http.MethodPost,
					Path:    "/user/aux-dept",
					Handler: organization.AddUserAuxDeptHandler(serverCtx),
				},
				{
					// 设置用户主部门
					Method:  http.MethodPost,
					Path:    "/user/primary-dept",
					Handler: organization.SetUserPrimaryDeptHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/system"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取当前用户信息
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				// 退出登录
				Method:  http.MethodPost,
				Path:    "/user/logout",
				Handler: user.LogoutHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user_public.LoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user_public.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取统计数据
				Method:  http.MethodGet,
				Path:    "/statistics",
				Handler: user_management.GetStatisticsHandler(serverCtx),
			},
			{
				// 用户列表查询
				Method:  http.MethodGet,
				Path:    "/users",
				Handler: user_management.ListUsersHandler(serverCtx),
			},
			{
				// 创建用户
				Method:  http.MethodPost,
				Path:    "/users",
				Handler: user_management.CreateUserHandler(serverCtx),
			},
			{
				// 用户详情查询
				Method:  http.MethodGet,
				Path:    "/users/:id",
				Handler: user_management.GetUserHandler(serverCtx),
			},
			{
				// 更新用户
				Method:  http.MethodPut,
				Path:    "/users/:id",
				Handler: user_management.UpdateUserHandler(serverCtx),
			},
			{
				// 删除用户
				Method:  http.MethodDelete,
				Path:    "/users/:id",
				Handler: user_management.DeleteUserHandler(serverCtx),
			},
			{
				// 重置用户密码
				Method:  http.MethodPost,
				Path:    "/users/:id/reset-password",
				Handler: user_management.ResetPasswordHandler(serverCtx),
			},
			{
				// 解锁用户
				Method:  http.MethodPost,
				Path:    "/users/:id/unlock",
				Handler: user_management.UnlockUserHandler(serverCtx),
			},
			{
				// 批量导入用户
				Method:  http.MethodPost,
				Path:    "/users/batch-import",
				Handler: user_management.BatchImportHandler(serverCtx),
			},
			{
				// 批量更新用户状态
				Method:  http.MethodPost,
				Path:    "/users/batch-status",
				Handler: user_management.BatchUpdateStatusHandler(serverCtx),
			},
			{
				// 导出用户数据
				Method:  http.MethodGet,
				Path:    "/users/export",
				Handler: user_management.ExportUsersHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user_management"),
	)
}
