import {
    Layout, Database, GitMerge, Server, Layers,
    Search, FileText, Activity, Cpu, Link,
    RefreshCw, ChevronRight, Shield, CheckSquare,
    Plus, Upload, FileCheck, TrendingUp, MoreHorizontal, X, AlertTriangle, User, Users, Clock, MessageCircle, Send,
    Book, Tag, CheckCircle, ArrowRight, Sparkles, Box, Edit, XCircle, ZoomIn, ZoomOut, Eye, Share2, Network, GitBranch, Table, Globe, ChevronDown, Check,
    ScanText, Verified, Lock, History, Bookmark, LayoutGrid, Building2, UserCog, PanelLeftClose, Grip, Settings,
    BarChart3, PieChart, FileBarChart, LineChart, TrendingDown, Home, Menu, Save, Download, Trash2,
    Archive, Star, Heart, ThumbsUp, Flag, Award, Trophy, Zap, Power, Battery, Wifi, Bluetooth, Radio, Tv, Monitor,
    Smartphone, Tablet, Laptop, Printer, Key, Unlock, EyeOff, ShieldCheck, ShieldAlert, Info, HelpCircle,
    AlertCircle, CheckCircle2, Minus, Calendar, Bell, Mail, Phone, MapPin, Camera, Image, Video, Music, File, FolderOpen,
    // 新增常用图标（只包含确定存在的）
    Cloud, CloudUpload, CloudDownload,
    Files, FileCode, FileJson, BookOpen,
    Wrench, Hammer, Plug, PlugZap,
    MessageSquare,
    Fingerprint, UserPlus, UserMinus, UserX, UserCheck, UserCircle,
    Rocket, Target, Compass, Map, Earth,
    GitCommit, GitPullRequest, GitCompare, GitFork,
    FolderTree, FolderPlus, FolderMinus, FolderSearch, FolderSync,
    Package2, Boxes,
    Lightbulb,
    Play, Pause,
    Repeat, Shuffle,
    Volume2, VolumeX, Headphones,
    Mic, MicOff,
    ShoppingBag, ShoppingBasket, CreditCard,
    Receipt, Ticket, QrCode, Barcode,
    Clipboard, ClipboardCheck, ClipboardList, ClipboardCopy,
    StickyNote, Notebook,
    PenTool, Palette,
    Layers2, Layers3,
    Grid3x3, Columns,
    AlignLeft, AlignCenter, AlignRight,
    Bold, Italic, Underline,
    List, ListOrdered,
    Hash, AtSign, Percent,
    DollarSign,
    ArrowUp, ArrowDown, ArrowLeft,
    Move,
    Maximize, Minimize,
    RotateCw, RotateCcw,
    Crop, Scissors, Eraser,
    Filter, Sliders,
    ChevronUp, ChevronLeft,
    MoreVertical,
    Copy,
    ExternalLink,
    Code,
    HardDrive,
    Router,
    Sun, Moon,
    Briefcase,
    Car,
    Circle,
    Square,
    Triangle,
    Sparkle,
    Bolt,
    Usb,
    Navigation,
    Pin,
    Scan,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

// 图标名称到组件的映射
const ICON_NAME_MAP: Record<string, LucideIcon> = {
    'Layout': Layout,
    'Database': Database,
    'GitMerge': GitMerge,
    'Server': Server,
    'Layers': Layers,
    'Search': Search,
    'FileText': FileText,
    'Activity': Activity,
    'Cpu': Cpu,
    'Link': Link,
    'RefreshCw': RefreshCw,
    'ChevronRight': ChevronRight,
    'Shield': Shield,
    'CheckSquare': CheckSquare,
    'Plus': Plus,
    'Upload': Upload,
    'FileCheck': FileCheck,
    'TrendingUp': TrendingUp,
    'MoreHorizontal': MoreHorizontal,
    'X': X,
    'AlertTriangle': AlertTriangle,
    'User': User,
    'Users': Users,
    'Clock': Clock,
    'MessageCircle': MessageCircle,
    'Send': Send,
    'Book': Book,
    'Tag': Tag,
    'CheckCircle': CheckCircle,
    'ArrowRight': ArrowRight,
    'Sparkles': Sparkles,
    'Box': Box,
    'Edit': Edit,
    'XCircle': XCircle,
    'ZoomIn': ZoomIn,
    'ZoomOut': ZoomOut,
    'Eye': Eye,
    'Share2': Share2,
    'Network': Network,
    'GitBranch': GitBranch,
    'Table': Table,
    'Globe': Globe,
    'ChevronDown': ChevronDown,
    'Check': Check,
    'ScanText': ScanText,
    'Verified': Verified,
    'Lock': Lock,
    'History': History,
    'Bookmark': Bookmark,
    'LayoutGrid': LayoutGrid,
    'Building2': Building2,
    'UserCog': UserCog,
    'PanelLeftClose': PanelLeftClose,
    'Grip': Grip,
    'Settings': Settings,
    'BarChart3': BarChart3,
    'PieChart': PieChart,
    'FileBarChart': FileBarChart,
    'LineChart': LineChart,
    'TrendingDown': TrendingDown,
    'Home': Home,
    'Menu': Menu,
    'Save': Save,
    'Download': Download,
    'Trash2': Trash2,
    'Archive': Archive,
    'Star': Star,
    'Heart': Heart,
    'ThumbsUp': ThumbsUp,
    'Flag': Flag,
    'Award': Award,
    'Trophy': Trophy,
    'Zap': Zap,
    'Power': Power,
    'Battery': Battery,
    'Wifi': Wifi,
    'Bluetooth': Bluetooth,
    'Radio': Radio,
    'Tv': Tv,
    'Monitor': Monitor,
    'Smartphone': Smartphone,
    'Tablet': Tablet,
    'Laptop': Laptop,
    'Printer': Printer,
    'Key': Key,
    'Unlock': Unlock,
    'EyeOff': EyeOff,
    'ShieldCheck': ShieldCheck,
    'ShieldAlert': ShieldAlert,
    'Info': Info,
    'HelpCircle': HelpCircle,
    'AlertCircle': AlertCircle,
    'CheckCircle2': CheckCircle2,
    'Minus': Minus,
    'Calendar': Calendar,
    'Bell': Bell,
    'Mail': Mail,
    'Phone': Phone,
    'MapPin': MapPin,
    'Camera': Camera,
    'Image': Image,
    'Video': Video,
    'Music': Music,
    'File': File,
    'FolderOpen': FolderOpen,
    // 新增图标映射（只包含确定存在的）
    'Cloud': Cloud,
    'CloudUpload': CloudUpload,
    'CloudDownload': CloudDownload,
    'Files': Files,
    'FileCode': FileCode,
    'FileJson': FileJson,
    'BookOpen': BookOpen,
    'Wrench': Wrench,
    'Hammer': Hammer,
    'Plug': Plug,
    'PlugZap': PlugZap,
    'MessageSquare': MessageSquare,
    'Fingerprint': Fingerprint,
    'UserPlus': UserPlus,
    'UserMinus': UserMinus,
    'UserX': UserX,
    'UserCheck': UserCheck,
    'UserCircle': UserCircle,
    'Rocket': Rocket,
    'Target': Target,
    'Compass': Compass,
    'Map': Map,
    'Earth': Earth,
    'GitCommit': GitCommit,
    'GitPullRequest': GitPullRequest,
    'GitCompare': GitCompare,
    'GitFork': GitFork,
    'FolderTree': FolderTree,
    'FolderPlus': FolderPlus,
    'FolderMinus': FolderMinus,
    'FolderSearch': FolderSearch,
    'FolderSync': FolderSync,
    'Package2': Package2,
    'Boxes': Boxes,
    'Lightbulb': Lightbulb,
    'Play': Play,
    'Pause': Pause,
    'Repeat': Repeat,
    'Shuffle': Shuffle,
    'Volume2': Volume2,
    'VolumeX': VolumeX,
    'Headphones': Headphones,
    'Mic': Mic,
    'MicOff': MicOff,
    'ShoppingBag': ShoppingBag,
    'ShoppingBasket': ShoppingBasket,
    'CreditCard': CreditCard,
    'Receipt': Receipt,
    'Ticket': Ticket,
    'QrCode': QrCode,
    'Barcode': Barcode,
    'Clipboard': Clipboard,
    'ClipboardCheck': ClipboardCheck,
    'ClipboardList': ClipboardList,
    'ClipboardCopy': ClipboardCopy,
    'StickyNote': StickyNote,
    'Notebook': Notebook,
    'PenTool': PenTool,
    'Palette': Palette,
    'Layers2': Layers2,
    'Layers3': Layers3,
    'Grid3x3': Grid3x3,
    'Columns': Columns,
    'AlignLeft': AlignLeft,
    'AlignCenter': AlignCenter,
    'AlignRight': AlignRight,
    'Bold': Bold,
    'Italic': Italic,
    'Underline': Underline,
    'List': List,
    'ListOrdered': ListOrdered,
    'Hash': Hash,
    'AtSign': AtSign,
    'Percent': Percent,
    'DollarSign': DollarSign,
    'ArrowUp': ArrowUp,
    'ArrowDown': ArrowDown,
    'ArrowLeft': ArrowLeft,
    'Move': Move,
    'Maximize': Maximize,
    'Minimize': Minimize,
    'RotateCw': RotateCw,
    'RotateCcw': RotateCcw,
    'Crop': Crop,
    'Scissors': Scissors,
    'Eraser': Eraser,
    'Filter': Filter,
    'Sliders': Sliders,
    'ChevronUp': ChevronUp,
    'ChevronLeft': ChevronLeft,
    'MoreVertical': MoreVertical,
    'Copy': Copy,
    'ExternalLink': ExternalLink,
    'Code': Code,
    'HardDrive': HardDrive,
    'Router': Router,
    'Sun': Sun,
    'Moon': Moon,
    'Briefcase': Briefcase,
    'Car': Car,
    'Circle': Circle,
    'Square': Square,
    'Triangle': Triangle,
    'Sparkle': Sparkle,
    'Bolt': Bolt,
    'Usb': Usb,
    'Navigation': Navigation,
    'Pin': Pin,
    'Scan': Scan,
};

/**
 * 根据图标名称获取图标组件
 * @param iconName 图标名称（如 'Layout', 'Database'）
 * @param defaultIcon 默认图标（如果找不到时使用）
 * @returns 图标组件
 */
export function getIconByName(iconName?: string, defaultIcon: LucideIcon = LayoutGrid): LucideIcon {
    if (!iconName) {
        return defaultIcon;
    }
    const icon = ICON_NAME_MAP[iconName];
    // 确保返回的是一个有效的函数组件，否则返回默认图标
    if (!icon) {
        return defaultIcon;
    }
    // 验证返回的是函数类型（lucide-react 图标都是函数组件）
    if (typeof icon !== 'function') {
        console.warn(`Icon "${iconName}" is not a function component, using default icon.`, { icon, type: typeof icon });
        return defaultIcon;
    }
    return icon;
}
