// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BindPermissionReq struct {
	Id               string `path:"id"`                         // UUID v7
	PermissionKey    string `json:"permission_key,optional"`    // 已有权限标识
	CreatePermission bool   `json:"create_permission,optional"` // 是否创建新权限
	PermissionName   string `json:"permission_name,optional"`   // 新权限名称
}

type BindPermissionResp struct {
	Menu Menu `json:"menu"`
}

type CreateMenuReq struct {
	Name             string `json:"name" validate:"required,min=1,max=128"`
	Code             string `json:"code" validate:"required,min=1,max=128"`
	Type             string `json:"type" validate:"required,oneof=directory page external button"`
	GroupId          string `json:"group_id,optional"`
	ParentId         string `json:"parent_id,optional"`
	Path             string `json:"path,optional"` // page/directory 使用
	RouteName        string `json:"route_name,optional"`
	ComponentKey     string `json:"component_key,optional"`
	ExternalUrl      string `json:"external_url,optional"` // external 类型必填
	OpenMode         string `json:"open_mode,optional"`    // external 类型必填：new/iframe/same
	PermissionKey    string `json:"permission_key,optional"`
	Icon             string `json:"icon,optional"` // 图标名称（如 Layout, Database）
	Visible          bool   `json:"visible,optional"`
	Enabled          bool   `json:"enabled,optional"`
	Order            int    `json:"order,optional"` // 默认插入同级末尾
	ShowInNav        bool   `json:"show_in_nav,optional"`
	Cacheable        bool   `json:"cacheable,optional"`
	CreatePermission bool   `json:"create_permission,optional"` // 是否创建新权限（需权限服务联动）
	PermissionName   string `json:"permission_name,optional"`   // 新权限名称（create_permission=true时必填）
}

type CreateMenuResp struct {
	Menu Menu `json:"menu"`
}

type DeleteMenuReq struct {
	Id      string `path:"id"`               // UUID v7
	Cascade bool   `form:"cascade,optional"` // 是否级联删除（默认false）
}

type DeleteMenuResp struct {
	ImpactInfo ImpactInfo `json:"impact_info,optional"` // 影响面信息
}

type GetMenuAuditsReq struct {
	Id            string `path:"id"` // UUID v7
	Page          int    `form:"page,default=1" validate:"min=1"`
	PageSize      int    `form:"page_size,default=10" validate:"min=1,max=100"`
	OperationType string `form:"operation_type,optional"` // 操作类型筛选
	OperatorId    string `form:"operator_id,optional"`    // 操作人ID筛选
	StartTime     string `form:"start_time,optional"`     // 开始时间
	EndTime       string `form:"end_time,optional"`       // 结束时间
}

type GetMenuAuditsResp struct {
	Total    int64          `json:"total"`
	Page     int            `json:"page"`
	PageSize int            `json:"page_size"`
	Logs     []MenuAuditLog `json:"logs"`
}

type GetMenuInspectionResp struct {
	Risks []RiskItem `json:"risks"`
}

type GetMenuReq struct {
	Id string `path:"id"` // UUID v7
}

type GetMenuResp struct {
	Menu         Menu         `json:"menu"`
	AuditSummary AuditSummary `json:"audit_summary,optional"` // 最近一次操作摘要
}

type GetMenuStatsResp struct {
	Total             int64 `json:"total"`              // 总菜单数
	Enabled           int64 `json:"enabled"`            // 启用菜单数
	Hidden            int64 `json:"hidden"`             // 隐藏菜单数
	UnboundPermission int64 `json:"unbound_permission"` // 未绑定权限菜单数（高风险）
}

type GetMenuTreeReq struct {
	Keyword        string `form:"keyword,optional"`         // 搜索关键词（name/code/path/permission_key）
	Enabled        bool   `form:"enabled,optional"`         // 是否启用
	Visible        bool   `form:"visible,optional"`         // 是否可见
	PermissionBind string `form:"permission_bind,optional"` // 权限绑定状态：bound/unbound
	Type           string `form:"type,optional"`            // 类型：directory/page/external/button
	GroupId        string `form:"group_id,optional"`        // 分组ID
}

type GetMenuTreeResp struct {
	Menus []Menu `json:"menus"`
}

type MoveMenuReq struct {
	Id          string `path:"id"`                                  // UUID v7
	NewParentId string `json:"new_parent_id,optional"`              // 新父级ID（空表示移到根节点）
	NewOrder    int    `json:"new_order" validate:"required,min=0"` // 新位置（同级排序）
}

type MoveMenuResp struct {
	Menu Menu `json:"menu"`
}

type ReorderMenusReq struct {
	Updates []OrderUpdate `json:"updates" validate:"required,min=1"`
}

type ReorderMenusResp struct {
	SuccessCount int                  `json:"success_count"`
	FailedCount  int                  `json:"failed_count"`
	Errors       []MenuOperationError `json:"errors,optional"`
}

type ToggleMenuEnabledReq struct {
	Id      string `path:"id"` // UUID v7
	Enabled bool   `json:"enabled" validate:"required"`
}

type ToggleMenuEnabledResp struct {
	Menu Menu `json:"menu"`
}

type ToggleMenuVisibleReq struct {
	Id      string `path:"id"` // UUID v7
	Visible bool   `json:"visible" validate:"required"`
}

type ToggleMenuVisibleResp struct {
	Menu Menu `json:"menu"`
}

type UpdateMenuReq struct {
	Id            string `path:"id"` // UUID v7
	Name          string `json:"name,optional" validate:"omitempty,min=1,max=128"`
	Code          string `json:"code,optional" validate:"omitempty,min=1,max=128"`
	Type          string `json:"type,optional" validate:"omitempty,oneof=directory page external button"`
	GroupId       string `json:"group_id,optional"`
	ParentId      string `json:"parent_id,optional"`
	Path          string `json:"path,optional"`
	RouteName     string `json:"route_name,optional"`
	ComponentKey  string `json:"component_key,optional"`
	ExternalUrl   string `json:"external_url,optional"`
	OpenMode      string `json:"open_mode,optional"`
	PermissionKey string `json:"permission_key,optional"`
	Icon          string `json:"icon,optional"` // 图标名称（如 Layout, Database）
	Visible       bool   `json:"visible,optional"`
	Enabled       bool   `json:"enabled,optional"`
	Order         int    `json:"order,optional"`
	ShowInNav     bool   `json:"show_in_nav,optional"`
	Cacheable     bool   `json:"cacheable,optional"`
}

type UpdateMenuResp struct {
	Menu Menu `json:"menu"`
}
