// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddUserAuxDeptReq struct {
	UserId string `json:"userId" validate:"required"`
	DeptId string `json:"deptId" validate:"required"`
}

type AddUserAuxDeptResp struct {
	Success bool `json:"success"`
}

type CreateOrgReq struct {
	ParentId  string `json:"parentId,optional,default=0" validate:"required"`
	Name      string `json:"name" validate:"required,max=100"`
	Code      string `json:"code,optional" validate:"omitempty,max=50"`
	SortOrder int    `json:"sortOrder,optional,default=0"`
	LeaderId  string `json:"leaderId,optional"`
	Type      int8   `json:"type,optional,default=2" validate:"oneof=1 2"`
	Desc      string `json:"desc,optional" validate:"max=255"`
}

type CreateOrgResp struct {
	Id string `json:"id"`
}

type DeleteOrgReq struct {
	Id string `path:"id" validate:"required"`
}

type DeleteOrgResp struct {
	Success bool `json:"success"`
}

type GetOrgDetailReq struct {
	Id string `path:"id" validate:"required"`
}

type GetOrgDetailResp struct {
	Detail *OrgDetail `json:"detail"`
}

type GetOrgTreeReq struct {
	Name   string `json:"name,optional"`   // 模糊搜索
	Status int8   `json:"status,optional"` // 状态过滤
}

type GetOrgTreeResp struct {
	Tree []*OrgTreeNode `json:"tree"`
}

type GetOrgUsersReq struct {
	Id        string `path:"id" validate:"required"`
	Recursive bool   `json:"recursive,optional,default=false"` // 是否递归查询子部门
}

type GetOrgUsersResp struct {
	Users []*DeptUser `json:"users"`
}

type MoveOrgReq struct {
	Id             string   `json:"id" validate:"required"`
	TargetParentId string   `json:"targetParentId" validate:"required"`
	SortOrders     []string `json:"sortOrders,optional"` // 同级排序ID列表
}

type MoveOrgResp struct {
	Success bool `json:"success"`
}

type RemoveUserAuxDeptReq struct {
	UserId string `path:"userId" validate:"required"`
	DeptId string `path:"deptId" validate:"required"`
}

type RemoveUserAuxDeptResp struct {
	Success bool `json:"success"`
}

type SetUserPrimaryDeptReq struct {
	UserId string `json:"userId" validate:"required"`
	DeptId string `json:"deptId" validate:"required"`
}

type SetUserPrimaryDeptResp struct {
	Success bool `json:"success"`
}

type UpdateOrgReq struct {
	Id        string `path:"id" validate:"required"`
	Name      string `json:"name,optional" validate:"omitempty,max=100"`
	Code      string `json:"code,optional" validate:"omitempty,max=50"`
	SortOrder int    `json:"sortOrder,optional"`
	LeaderId  string `json:"leaderId,optional"`
	Status    int8   `json:"status,optional" validate:"oneof=0 1"`
	Desc      string `json:"desc,optional" validate:"max=255"`
}

type UpdateOrgResp struct {
	Success bool `json:"success"`
}
