// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ClonePermissionTemplateReq struct {
	Id   string `path:"id"` // UUID v7
	Name string `json:"name" validate:"required,max=128"`
	Code string `json:"code" validate:"required,max=64,lowercase_alphanum"`
}

type ClonePermissionTemplateResp struct {
	Id string `json:"id"`
}

type CreatePermissionTemplateReq struct {
	Name            string                       `json:"name" validate:"required,max=128"`
	Code            string                       `json:"code" validate:"required,max=64,lowercase_alphanum"`
	Description     string                       `json:"description" validate:"max=500"`
	ScopeSuggestion string                       `json:"scope_suggestion" validate:"omitempty,oneof=global organization domain project"`
	PolicyMatrix    map[string]PolicyMatrixEntry `json:"policy_matrix" validate:"required"`
	AdvancedPerms   map[string]AdvancedPermEntry `json:"advanced_perms"`
}

type CreatePermissionTemplateResp struct {
	Id string `json:"id"`
}

type DeletePermissionTemplateReq struct {
	Id string `path:"id"` // UUID v7
}

type DeletePermissionTemplateResp struct {
	Success bool `json:"success"`
}

type DisablePermissionTemplateReq struct {
	Id string `path:"id"` // UUID v7
}

type DisablePermissionTemplateResp struct {
	Success bool `json:"success"`
}

type EnablePermissionTemplateReq struct {
	Id string `path:"id"` // UUID v7
}

type EnablePermissionTemplateResp struct {
	Success bool `json:"success"`
}

type GetPermissionTemplateReq struct {
	Id string `path:"id"` // UUID v7
}

type GetPermissionTemplateResp struct {
	Data PermissionTemplateDetail `json:"data"`
}

type ListPermissionTemplatesReq struct {
	Keyword         string `json:"keyword" validate:"max=128"`
	Status          string `json:"status" validate:"omitempty,oneof=draft published disabled"`
	ScopeSuggestion string `json:"scope_suggestion" validate:"omitempty,oneof=global organization domain project"`
	Page            int    `json:"page" validate:"min=1"`
	PageSize        int    `json:"page_size" validate:"min=1,max=100"`
}

type ListPermissionTemplatesResp struct {
	Total int64                    `json:"total"`
	Data  []PermissionTemplateItem `json:"data"`
}

type PublishPermissionTemplateReq struct {
	Id string `path:"id"` // UUID v7
}

type PublishPermissionTemplateResp struct {
	Success bool `json:"success"`
	Version int  `json:"version"`
}

type UpdatePermissionTemplateReq struct {
	Id              string                       `path:"id" json:"id" validate:"required"`
	Name            string                       `json:"name" validate:"required,max=128"`
	Code            string                       `json:"code" validate:"required,max=64,lowercase_alphanum"`
	Description     string                       `json:"description" validate:"max=500"`
	ScopeSuggestion string                       `json:"scope_suggestion" validate:"omitempty,oneof=global organization domain project"`
	PolicyMatrix    map[string]PolicyMatrixEntry `json:"policy_matrix" validate:"required"`
	AdvancedPerms   map[string]AdvancedPermEntry `json:"advanced_perms"`
}

type UpdatePermissionTemplateResp struct {
	Success bool `json:"success"`
}
