// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AuditLog struct {
	Id         int64                  `json:"id"`
	Action     string                 `json:"action"`
	Operator   string                 `json:"operator"`
	OperatorId string                 `json:"operator_id"`
	Changes    map[string]interface{} `json:"changes,optional"`
	Timestamp  string                 `json:"timestamp"`
}

type HealthResp struct {
	Status string `json:"status"`
}

type IdReq struct {
	Id int64 `path:"id"`
}

type IdsReq struct {
	Ids []int64 `json:"ids"`
}

type ImportError struct {
	Row    int    `json:"row"`
	Field  string `json:"field"`
	Reason string `json:"reason"`
}

type KeywordInfo struct {
	Keyword string `form:"keyword,optional"` // 关键字查询
}

type OperationError struct {
	UserId string `json:"user_id"`
	Reason string `json:"reason"`
}

type PageBaseInfo struct {
	Offset int `form:"offset,default=1,range=[1:]"`     // 页码，默认1
	Limit  int `form:"limit,default=10,range=[0:2000]"` // 每页大小，默认10，0表示不分页
}

type PageInfo struct {
	PageBaseInfo
	Direction string `form:"direction,default=desc,options=asc|desc"`               // 排序方向：asc 正序，desc 倒序
	Sort      string `form:"sort,default=created_at,options=created_at|updated_at"` // 排序字段
}

type PageInfoWithKeyword struct {
	PageInfo
	KeywordInfo
}

type PageResp struct {
	Entries    interface{} `json:"entries"`     // 数据列表
	TotalCount int64       `json:"total_count"` // 总记录数
}

type RoleBinding struct {
	Id             int64  `json:"id"`
	UserId         string `json:"user_id"`
	OrgId          string `json:"org_id"`
	Position       string `json:"position,optional"`
	PermissionRole string `json:"permission_role,optional"`
}

type RoleBindingInput struct {
	OrgId          string `json:"org_id" validate:"required"`
	Position       string `json:"position,optional"`
	PermissionRole string `json:"permission_role,optional"`
}

type User struct {
	Id            string `json:"id"`
	Name          string `json:"name"`
	Email         string `json:"email"`
	Phone         string `json:"phone,optional"`
	DeptId        string `json:"dept_id,optional"`
	Status        int8   `json:"status"`
	AccountSource string `json:"account_source"`
	LastLogin     string `json:"last_login,optional"`
	CreatedAt     string `json:"created_at"`
	CreatedBy     string `json:"created_by,optional"`
	UpdatedAt     string `json:"updated_at"`
	UpdatedBy     string `json:"updated_by,optional"`
}

type UserInfo struct {
	Id           string `json:"id"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	Organization string `json:"organization,optional"`
}
