// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AuditLog struct {
	Id         int64                  `json:"id"`
	Action     string                 `json:"action"`
	Operator   string                 `json:"operator"`
	OperatorId string                 `json:"operator_id"`
	Changes    map[string]interface{} `json:"changes,optional"`
	Timestamp  string                 `json:"timestamp"`
}

type AuditSummary struct {
	LastOperatorId   string `json:"last_operator_id,optional"`
	LastOperatorName string `json:"last_operator_name,optional"`
	LastOperationAt  string `json:"last_operation_at,optional"`
}

type HealthResp struct {
	Status string `json:"status"`
}

type IdReq struct {
	Id int64 `path:"id"`
}

type IdsReq struct {
	Ids []int64 `json:"ids"`
}

type ImpactInfo struct {
	ChildrenCount int `json:"children_count"` // 子菜单数量
}

type ImportError struct {
	Row    int    `json:"row"`
	Field  string `json:"field"`
	Reason string `json:"reason"`
}

type KeywordInfo struct {
	Keyword string `form:"keyword,optional"` // 关键字查询
}

type Menu struct {
	Id            string   `json:"id"` // UUID v7
	Name          string   `json:"name"`
	Code          string   `json:"code"`
	Type          string   `json:"type"` // directory/page/external/button
	GroupId       string   `json:"group_id,optional"`
	ParentId      string   `json:"parent_id,optional"`
	Path          string   `json:"path,optional"`
	RouteName     string   `json:"route_name,optional"`
	ComponentKey  string   `json:"component_key,optional"`
	ExternalUrl   string   `json:"external_url,optional"`
	OpenMode      string   `json:"open_mode,optional"` // new/iframe/same
	PermissionKey string   `json:"permission_key,optional"`
	Visible       bool     `json:"visible"`
	Enabled       bool     `json:"enabled"`
	Order         int      `json:"order"`
	ShowInNav     bool     `json:"show_in_nav"`
	Cacheable     bool     `json:"cacheable"`
	ChildrenCount int      `json:"children_count"`      // 子节点数量
	RiskFlags     []string `json:"risk_flags,optional"` // 风险标记：UNBOUND_PERMISSION/ROUTE_CONFLICT/ORDER_CONFLICT
	CreatedAt     string   `json:"created_at"`
	CreatedBy     string   `json:"created_by,optional"`
	UpdatedAt     string   `json:"updated_at"`
	UpdatedBy     string   `json:"updated_by,optional"`
	Children      []Menu   `json:"children,optional"` // 子菜单（树形结构）
}

type MenuAuditLog struct {
	Id            string                 `json:"id"`
	MenuId        string                 `json:"menu_id"`
	OperationType string                 `json:"operation_type"`
	OperatorId    string                 `json:"operator_id,optional"`
	OperatorName  string                 `json:"operator_name,optional"`
	ChangedFields []string               `json:"changed_fields,optional"` // 变更字段列表
	OldValue      map[string]interface{} `json:"old_value,optional"`      // 旧值（JSON）
	NewValue      map[string]interface{} `json:"new_value,optional"`      // 新值（JSON）
	Remark        string                 `json:"remark,optional"`
	CreatedAt     string                 `json:"created_at"`
}

type MenuOperationError struct {
	Id     string `json:"id"`
	Reason string `json:"reason"`
}

type OperationError struct {
	UserId string `json:"user_id"`
	Reason string `json:"reason"`
}

type OrderUpdate struct {
	Id    string `json:"id" validate:"required"` // UUID v7
	Order int    `json:"order" validate:"required,min=0"`
}

type PageBaseInfo struct {
	Offset int `form:"offset,default=1,range=[1:]"`     // 页码，默认1
	Limit  int `form:"limit,default=10,range=[0:2000]"` // 每页大小，默认10，0表示不分页
}

type PageInfo struct {
	PageBaseInfo
	Direction string `form:"direction,default=desc,options=asc|desc"`               // 排序方向：asc 正序，desc 倒序
	Sort      string `form:"sort,default=created_at,options=created_at|updated_at"` // 排序字段
}

type PageInfoWithKeyword struct {
	PageInfo
	KeywordInfo
}

type PageResp struct {
	Entries    interface{} `json:"entries"`     // 数据列表
	TotalCount int64       `json:"total_count"` // 总记录数
}

type RiskItem struct {
	MenuId      string `json:"menu_id"`
	MenuName    string `json:"menu_name"`
	MenuCode    string `json:"menu_code"`
	RiskType    string `json:"risk_type"` // UNBOUND_PERMISSION/ROUTE_CONFLICT/ORDER_CONFLICT
	Description string `json:"description"`
}

type RoleBinding struct {
	Id             int64  `json:"id"`
	UserId         string `json:"user_id"`
	OrgId          string `json:"org_id"`
	Position       string `json:"position,optional"`
	PermissionRole string `json:"permission_role,optional"`
}

type RoleBindingInput struct {
	OrgId          string `json:"org_id" validate:"required"`
	Position       string `json:"position,optional"`
	PermissionRole string `json:"permission_role,optional"`
}

type User struct {
	Id            string `json:"id"`
	Name          string `json:"name"`
	Email         string `json:"email"`
	Phone         string `json:"phone,optional"`
	DeptId        string `json:"dept_id,optional"`
	Status        int8   `json:"status"`
	AccountSource string `json:"account_source"`
	LastLogin     string `json:"last_login,optional"`
	CreatedAt     string `json:"created_at"`
	CreatedBy     string `json:"created_by,optional"`
	UpdatedAt     string `json:"updated_at"`
	UpdatedBy     string `json:"updated_by,optional"`
}

type UserInfo struct {
	Id           string `json:"id"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	Organization string `json:"organization,optional"`
}
