// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetUserInfoResp struct {
	UserInfo UserInfo `json:"user_info"`
}

type LogoutResp struct {
	Message string `json:"message"`
}
