// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BatchImportReq struct {
	DryRun bool `form:"dry_run,optional"`
}

type BatchImportResp struct {
	TotalRows    int           `json:"total_rows"`
	SuccessCount int           `json:"success_count"`
	FailedCount  int           `json:"failed_count"`
	Errors       []ImportError `json:"errors,optional"`
	UserIds      []string      `json:"user_ids"`
}

type BatchUpdateStatusReq struct {
	UserIds []string `json:"user_ids" validate:"required,min=1,max=100"`
	Status  int8     `json:"status" validate:"required,oneof=1 2 3 4"`
	Reason  string   `json:"reason,optional"`
}

type BatchUpdateStatusResp struct {
	SuccessCount int              `json:"success_count"`
	FailedCount  int              `json:"failed_count"`
	Errors       []OperationError `json:"errors,optional"`
}

type CreateUserReq struct {
	Name            string             `json:"name" validate:"required,min=2,max=50"`
	Email           string             `json:"email" validate:"required,email"`
	Phone           string             `json:"phone,optional" validate:"omitempty,len=11"`
	DeptId          string             `json:"dept_id" validate:"required"`
	RoleBindings    []RoleBindingInput `json:"role_bindings,optional"`
	AccountSource   string             `json:"account_source" validate:"required,oneof=local sso"`
	SendInvitation  bool               `json:"send_invitation,optional"`
	InitialPassword string             `json:"initial_password,optional"`
}

type CreateUserResp struct {
	UserId          string `json:"user_id"`
	InitialPassword string `json:"initial_password,optional"`
}

type DeleteUserReq struct {
	TransferTo string `json:"transfer_to,optional"`
	Force      bool   `json:"force,optional"`
}

type DeleteUserResp struct {
	Archived           bool `json:"archived"`
	ImpactsTransferred bool `json:"impacts_transferred"`
}

type EmptyResp struct {
}

type GetStatisticsResp struct {
	Total            int64   `json:"total"`
	Active           int64   `json:"active"`
	Locked           int64   `json:"locked"`
	Inactive         int64   `json:"inactive"`
	NoOrgBinding     int64   `json:"no_org_binding"`
	NoPermissionRole int64   `json:"no_permission_role"`
	RecentActiveRate float64 `json:"recent_active_rate"`
}

type GetUserResp struct {
	User         User          `json:"user"`
	RoleBindings []RoleBinding `json:"role_bindings"`
	AuditLogs    []AuditLog    `json:"audit_logs"`
}

type ListUsersReq struct {
	Page           int    `form:"page,default=1" validate:"min=1"`
	PageSize       int    `form:"page_size,default=10" validate:"min=1,max=100"`
	Keyword        string `form:"keyword,optional"`
	DeptId         string `form:"dept_id,optional"`
	Status         int8   `form:"status,optional"`
	AccountSource  string `form:"account_source,optional"`
	PermissionRole string `form:"permission_role,optional"`
	SortField      string `form:"sort_field,optional"` // name,created_at,last_login
	SortOrder      string `form:"sort_order,optional"` // asc,desc
}

type ListUsersResp struct {
	Total    int64  `json:"total"`
	Page     int    `json:"page"`
	PageSize int    `json:"page_size"`
	Users    []User `json:"users"`
}

type ResetPasswordReq struct {
	NewPassword string `json:"new_password,optional"`
	SendEmail   bool   `json:"send_email,optional"`
}

type ResetPasswordResp struct {
	TemporaryPassword string `json:"temporary_password"`
}

type UnlockUserReq struct {
	Reason string `json:"reason,optional"`
}

type UpdateUserReq struct {
	Name         string             `json:"name,optional"`
	Phone        string             `json:"phone,optional"`
	DeptId       string             `json:"dept_id,optional"`
	RoleBindings []RoleBindingInput `json:"role_bindings,optional"`
}
